title: "Hervea.T"
description: "Data Analyst"
logo: /Portfolio_T_Data/assets/img/headshot_circle.png
show_downloads: true
theme: jekyll-theme-minimal

# If this is a *project* site (repo ≠ herveat.github.io), add:
url: "https://herveat.github.io"
baseurl: "/Portfolio_T_Data"
