title: "Hervea.T"
description: "Data Analyst"
logo: " https://avatars.githubusercontent.com/u/239309942?v=4 "
show_downloads: true
theme: jekyll-theme-minimal

# If this is a *project* site (repo ≠ herveat.github.io), add:
url: "https://herveat.github.io"
baseurl: "/Portfolio_T_Data"
